      SUBROUTINE ALLOC

      INCLUDE 'PUFCAV.INC'
      INCLUDE 'PUFCAVB.INC'
      INCLUDE 'PUFCAVC.INC'

        !     MODULE m_FOUT
      ALLOCATE(TT(NSTEP),XKT(NSTEP,6),XKTV(NSTEP,6))


C     MODULE GPROD
      ALLOCATE(XB(NBPZ,MBPZ),YB(NBPZ,MBPZ),ZB(NBPZ,MBPZ))
      ALLOCATE(XW(NWPZ,MBPZ),YW(NWPZ,MBPZ),ZW(NWPZ,MBPZ))
      ALLOCATE(XX_TMP(NWPZ,MBPZ),YY_TMP(NWPZ,MBPZ),ZZ_TMP(NWPZ,MBPZ))
c XM YU 12/2011
      allocate(xwvs3d(nwpz,mbpz),ywvs3d(nwpz,mbpz),zwvs3d(nwpz,mbpz))
c XM YU 12/2011
      ALLOCATE(XH(NHPZ,MHPZ),YH(NHPZ,MHPZ),ZH(NHPZ,MHPZ))
      ALLOCATE(XW1(NWPZ,MBPZ),YW1(NWPZ,MBPZ),ZW1(NWPZ,MBPZ))
      ALLOCATE(THT(MBPZ),THR(NBPZ),SB(NBHZ))
      ALLOCATE(YTC(NBHZ),YCC(NBHZ),TCC(NBHZ))
      ALLOCATE(XI(NBPZ),ETA(NBPZ))
      ALLOCATE(CONMRX(3,NBPZ,MBPZ),VECMRX(3,NBPZ,MBPZ),
     &         WAKVEC(3,NWPZ,MBPZ))
      ALLOCATE(ARCLNG(NSCZP,MBZ,2))

C     MODULE GPRODW
      ALLOCATE(XWO(NWPZ,MBPZ,KZ),YWO(NWPZ,MBPZ,KZ),ZWO(NWPZ,MBPZ,KZ))
      ALLOCATE(XWW(NWPZ,MBPZ,KZ),YWW(NWPZ,MBPZ,KZ),ZWW(NWPZ,MBPZ,KZ))

C     MODULE GINT
      ALLOCATE(RZ(MBPZ),RZSQ(MBPZ),PITCH(MBPZ),RAKE(MBPZ))
      ALLOCATE(SKEW(MBPZ),CHORD(MBPZ),CAMBR(MBPZ),THICK(MBPZ))

C     MODULE FVEL
      ALLOCATE(VOXW(NSCWZ),VOYW(NSCWZ),VOZW(NSCWZ))
      ALLOCATE(VTOTS(NPANZ),VXIB(NBZ,MBZ),VETAB(NBZ,MBZ))
      ALLOCATE(VINFSB(NBZ,MBZ),VXIH(NHBZ,MHBZ),VETAH(NHBZ,MHBZ))
      ALLOCATE(VINFSH(NHBZ,MHBZ),UXTOT(NBZ,MBZ),UYTOT(NBZ,MBZ))
      ALLOCATE(UZTOT(NBZ,MBZ),UXHTOT(NHBZ,MHBZ),UYHTOT(NHBZ,MHBZ))
      ALLOCATE(UZHTOT(NHBZ,MHBZ))
      ALLOCATE(VOX1(NPANZ),VOY1(NPANZ),VOZ1(NPANZ))

C     MODULE FVEL2
      ALLOCATE(UXTHTOT(NHMX,MCAVM),UYTHTOT(NHMX,MCAVM))
      ALLOCATE(UZTHTOT(NHMX,MCAVM),UXCHTOT(NCAVM,MCAVM))
      ALLOCATE(UYCHTOT(NCAVM,MCAVM),UZCHTOT(NCAVM,MCAVM))

C     MODULE GEOMT
      ALLOCATE(XVP(NPANZ,4),YVP(NPANZ,4),XCT(NPANZ,3),DIR(NPANZ,3,3))
      ALLOCATE(SS(NPANZ,15),SID(NPANZ,4),GSX(NPANZ,4,3))
      ALLOCATE(GSW(NPANZ,4),VEL(NPANZ,6),DELU(NPANZ),DELV(NPANZ))
      ALLOCATE(COSPHI(NPANZ),SINPHI(NPANZ))

C     MODULE GEOMTP
      ALLOCATE(XCTP(NPANZ,3,KZ),DIRCP(NPANZ,3,3,KZ))
      ALLOCATE(XCTPW(NSCWZ,3,KZ),DIRWCP(NSCWZ,3,3,KZ))
      ALLOCATE(XCTPWs(NSCWZ,3,KZ),DIRWsCP(NSCWZ,3,3,KZ))
c XM YU
      allocate(xctpwv(nscwz,3,kz))
      ALLOCATE(XCTPDW(NDWMN,3,KZ),DIRDWCP(NDWMN,3,3,KZ))
      ALLOCATE(XCTPDWs(NSCWZ,3,KZ),DIRDWsCP(NSCWZ,3,3,KZ))
      ALLOCATE(XCPW(NSCWZ,3,KZ))

C     MODULE GEOMTW
      ALLOCATE(XVPW(NSCWZ,4),YVPW(NSCWZ,4),XCTW(NSCWZ,3))
      ALLOCATE(DIRW(NSCWZ,3,3),SSW(NSCWZ,15),SIDW(NSCWZ,4))
      ALLOCATE(GSXW(NSCWZ,4,3),GSWW(NSCWZ,4),VELW(NSCWZ,6))
      ALLOCATE(DELUW(NSCWZ),DELVW(NSCWZ),COSPHIW(NSCWZ))
      ALLOCATE(SINPHIW(NSCWZ))

C     MODULE GEOMTWD
      ALLOCATE(XVPWD(NDWMN,4),YVPWD(NDWMN,4),XCTWD(NDWMN,3))
      ALLOCATE(DIRWD(NDWMN,3,3),SSWD(NDWMN,15),SIDWD(NDWMN,4))
      ALLOCATE(GSXWD(NDWMN,4,3),GSWWD(NDWMN,4),VELWD(NDWMN,6))
      ALLOCATE(DELUWD(NDWMN),DELVWD(NDWMN),COSPHIWD(NDWMN))
      ALLOCATE(SINPHIWD(NDWMN))

C     MODULE GEOMTWO
      ALLOCATE(XVPWO(NSCWZ,4,KZ),YVPWO(NSCWZ,4,KZ),XCTWO(NSCWZ,3,KZ))
      ALLOCATE(DIRWO(NSCWZ,3,3,KZ),SSWO(NSCWZ,15,KZ),SIDWO(NSCWZ,4,KZ))
      ALLOCATE(GSXWO(NSCWZ,4,3,KZ),GSWWO(NSCWZ,4,KZ),VELWO(NSCWZ,6,KZ))
      ALLOCATE(DELUWO(NSCWZ,KZ),DELVWO(NSCWZ,KZ),COSPHIWO(NSCWZ,KZ))
      ALLOCATE(SINPHIWO(NSCWZ,KZ))

C     MODULE TOTG
      ALLOCATE(XG(NPANZ,4,3),CHRLEPS(NPANZ),CHRLEWS(NSCWZ))
      ALLOCATE(XGW(NSCWZ,4,3),chrlewso(NSCWZ,KZ))
      ALLOCATE(XGWD(NDWMN,4,3),CHRLEWSD(NDWMN))

      ALLOCATE(XG1(NPANZ,4,3),XG11(NPANZ,4,3),R111(NPANZ))

C     MODULE SIMQD1
      ALLOCATE(A(NPANZ),B(NPANZ),W(NPANZ,MBZ))
      ALLOCATE(CHDK(NPANZ),WDK(NPANZ),POT(NPANZ),DPDN(NPANZ))
      ALLOCATE(winf(npanz,mbz),CHDKDT(NPANZ),WD(NPANZ,MDMAX))
      ALLOCATE(WKD(NPAWZ,MDMAX))

C     MODULE SIMQD2
      ALLOCATE(AA(NTZ,NTZ),BB(NPANZ,NPANZ),C(NPANZ,NPAWZ))
      ALLOCATE(D(NPAWZ,NPANZ),E(NPAWZ,NPANZ),F(NPAWZ,NPAWZ))
      ALLOCATE(WK(NPAWZ,MBZ),WK2(NPAWZ,MBZ))
      ALLOCATE(WDK1(NPAWZ),CHDK1(NPAWZ),CHDKDT1(NPAWZ))

C     MODULE SIMQ1
      ALLOCATE(NPERB(NBLKMAX))

C     MODULE CORR
      ALLOCATE(DELCP(MBZ),DCPPRE(MBZ))

C     MODULE CIRC
! YE TIAN 04/08/2012
!     ALLOCATE(DELP(MBZ),DELPD(MDMAX))
      ALLOCATE(DELP(MBZ),DELPD(MDMAX),DELPonW(MBZ))

C     MODULE PRES
      ALLOCATE(CPB(NBZ,MBZ),CPH(NHBZ,MHBZ),DPDUB(NBZ,MBZ))
      ALLOCATE(DPDVB(NBZ,MBZ),DPDUH(NHBZ,MHBZ),DPDVH(NHBZ,MHBZ))

C     MODULE NORMAL
      ALLOCATE(XCON(NBHZP,MBPZ),YCON(NBHZP,MBPZ),ZCON(NBHZP,MBPZ))

C     MODULE FORCE
      ALLOCATE(BKFX(MBZ),BKFY(MBZ),BKFZ(MBZ),BKMX(MBZ),BKMY(MBZ))
      ALLOCATE(BKMZ(MBZ),HKFX(NHBZ),HKFY(NHBZ),HKFZ(NHBZ))
      ALLOCATE(HKMX(NHBZ),HKMY(NHBZ),HKMZ(NHBZ))

C     MODULE VFOR
      ALLOCATE(FVA(MBZ))

C     MODULE CAVGEOD
      ALLOCATE(DS(NBSCZ,MBZ),DZ(NBSCZ,MBZ))
      ALLOCATE(SZ(NBSCZP,MBZ),SPZ(NBSCZ,MBZ))
      ALLOCATE(RLAM(MBZ,2),CAVL(MBZ,2),CAVLP(MBZ,2),DZW(NWZ,MBZ))
      ALLOCATE(SOP(MBZ,2),CAVLSA(MBZ,NSTEP,2))

C     MODULE CAVGEOI
      ALLOCATE(M0(MBZ,2),JCV(MBZ,2),LCV(MBZ,2))
      ALLOCATE(NOCAV(MBZ,0:NSTEP,2))

C     MODULE CAVST
      ALLOCATE(QC(NSCZP,MBZ,2),PHI0(MBZ,2))
      ALLOCATE(PHI1(NSCZP,MBZ,2),DPHIDS(NSCZP,MBZ,2))
      ALLOCATE(DPHIDV(NBHZ,MBZ,2))

C     MODULE CVSOL2
      ALLOCATE(HT(NSCZP,MBZ,2),DPDNC(NPANZ),DELTA(MBZ,2))
      ALLOCATE(HTW1(MBZ),DELTAP(MBZ,2),SOL(NTZ),SORW(NPAWZ))
      ALLOCATE(POTW(NPAWZ),HTP(NBHZP,MBZ,2),HTWP(NWZ+1,MBZ))

C     MODULE SPLITD
      ALLOCATE(FLP(MBZ,2),FRP(MBZ,2),FLS(MBZ,2),FRS(MBZ,2))
      ALLOCATE(DZL(MBZ,2),DZR(MBZ,2),QSPR(MBZ,2),DLISP(MBZ,2))
      ALLOCATE(DPDVSP(MBZ,2),PHIL(MBZ,2),PHIR(MBZ,2),QSPL(MBZ,2))
      ALLOCATE(QSSR(MBZ))


C     MODULE NWAK
      ALLOCATE(NWC(MBZ,2),NWPAN(MBZ))

C     MODULE UVECB
      ALLOCATE(UL(NPANZ,3),VL(NPANZ,3),WL(NPANZ,3))

C     MODULE UVECBo
      ALLOCATE(ULo(NPANZ,3,KZ),VLo(NPANZ,3,KZ))
      ALLOCATE(WLo(NPANZ,3,KZ))

C     MODULE UVECW
      ALLOCATE(ULW(NSCWZ,3))

C     MODULE XTRAP
      ALLOCATE(CT(MBZ,4,2),DT(MBZ,4,2),QT(MBZ,4,2),QW(MBZ,4,2))

C     MODULE UNSWAKD
      ALLOCATE(WSTINF(NPANZ,MBZ),WSTINFD(NPANZ,MDMAX))

C     MODULE UNSDP
      ALLOCATE(DPHI(MBZ,0:NNDIM))

C     MODULE UNS
      ALLOCATE(POTM(NNDIM,NPANZ),DPDTPRE(NNDIM,NPANZ))
      ALLOCATE(POTWM(NNDIM,NPAWZ),DPDTPREW(NNDIM,NPAWZ))

C     MODULE TMPP1
      ALLOCATE(TEMP1(NPANZ),TEMP2(NPANZ),TEMP3(NPAWZ))
      ALLOCATE(TEMP4(NSCWZ),TEMP5(NPAWZ+MBZ))
      ALLOCATE(STRGTH(NPANZ,KZ),WUSINF(NPANZ,MBZ))
      ALLOCATE(STRGTH1(NSCWZ,KZ),WUSINF1(NSCWZ,MBZ))
      ALLOCATE(TEMPD4(NDWMN),STRGTHD(NPANZ,KZ))

C     MODULE CAVFB
      ALLOCATE(NNWC(MBZ),NWDIR(MBZ))

C     MODULE WAKSUBD
      ALLOCATE(XWS(NZWSUB,MBPZ),YWS(NZWSUB,MBPZ))
      ALLOCATE(ZWS(NZWSUB,MBPZ),WSUBIF(NPANZ,MBZ))
      ALLOCATE(WKFACE(NPAWZ,MBZ,NZWSUB),WSUBIF_IM(NPANZ,MBZ))

C     MODULE DWAKSUB
      ALLOCATE(XWSD(NZWSUB,MDMAXP),YWSD(NZWSUB,MDMAXP))
      ALLOCATE(ZWSD(NZWSUB,MDMAXP),WSUBIFD(NPANZ,MDMAX))

C     MODULE MEMSOL
      ALLOCATE(ALHS(NTZ,NTZ))

C     MODULE CVRHS
      ALLOCATE(RHS(NTZ))

C     MODULE PRESNO
      ALLOCATE(CPBN(NBZ,MBZ),CPHN(NHBZ,MHBZ))
      ALLOCATE(CPTNN(NTMAXT,NCMAXT),CPDN(NDMAX,MDMAX))
      ALLOCATE(CPTHN(NHMX,MCAVM),CPCN(NCAVM,MCAVM))

C     MODULE PODGEO1,PODGEO3,PODGEO4
      ALLOCATE(HRZ(NBPZ,MBPZ),HRZSQ(NBPZ,MBPZ))
      ALLOCATE(HRZP(NBZ,MBZ),HRZPSQ(NBZ,MBZ))

C     MODULE BKUTTA
      ALLOCATE(POTEMP(NTZ),WWK(NTZ,MBZ))

C     MODULE TOGBFLOW
      ALLOCATE(XCCC(NBHZP,MBPZ),YCCC(NBHZP,MBPZ))
      ALLOCATE(ZCCC(NBHZP,MBPZ),CPBMEAN(NSTEP,NBHZP,MBPZ))

C     MODULE GLOCBL
      ALLOCATE( XIV(NBPZ,MBPZ),ETAV(NBPZ,MBPZ) )

      IF(ISP.EQ.1) THEN

C     MODULE SPINT
        ALLOCATE(ICB(MBZ,2,NSTEP),MSW(MBZ,NSTEP),ICW(MBZ,NSTEP))
        ALLOCATE(IC(2,MBZ,NSTEP),IW(2,MBZ,NSTEP))
        ALLOCATE(ISUBM(NPBZ+NPHZ,NSTEP),ISUBH(NHBZ,NSTEP))
        ALLOCATE(NPERM(MBZ),ISUB1(MBZ,2,NSTEP),ISUWM(NPAWZ,NSTEP))
C     MODULE SPIMG
        ALLOCATE(XCTP_IM(NPBZ+NPHZ,3,KZ),XCPW_IM(NPAWZ,3,KZ))
      ENDIF

      IF(ISC.EQ.1) THEN
C     MODULE FXSR,CAVSR
        ALLOCATE(SSTE(MBZ),VELTE(MBZ,6))
        ALLOCATE(CT2(MBZ,4,2),QCSR(NCSRZP,MBZ,2),PHI0T(MBZ,2))
        ALLOCATE(PSI0T(MBZ,2),PHI2(NCSRZ,MBZ,2))
        ALLOCATE(DPHIDS2(NCSRZ,MBZ,2),DPHIDV2(NZSR2,MBZ,2))
        ALLOCATE(DELTAT1(MBZ),DELTATP(MBZ),CAVLT(MBZ))
        ALLOCATE(CAVLTP(MBZ),CAVLTSA(MBZ,NSTEP))
      ENDIF

      IF(ITUN.EQ.1) THEN
C     MODULE TNGEO
        ALLOCATE(XTUN(NtMAXt+1,NCMAXt+1),YTUN(NtMAXt+1,NCMAXt+1))
        ALLOCATE(ZTUN(NtMAXt+1,NCMAXt+1))
        ALLOCATE(VXITN(NTMAXT,NCMAXT),VETATN(NTMAXT,NCMAXT))
        ALLOCATE(VINFSTN(NTMAXT,NCMAXT))
        ALLOCATE(DPDUTN(NTMAXT,NCMAXT),DPDVTN(NTMAXT,NCMAXT))
        ALLOCATE(UXTNTOT(NTMAXT,NCMAXT),UYTNTOT(NTMAXT,NCMAXT))
        ALLOCATE(UZTNTOT(NTMAXT,NCMAXT),CPTN(NTMAXT,NCMAXT))
      ENDIF

      END SUBROUTINE
