C
C
C
      FUNCTION DASINH( X )
C
C     ARC-SINHYPERBOLIC FUNCTION; VALUE IS POSITIVE
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DATA ONE/1.0D0/
      DASINH=DLOG( X+DSQRT(X*X+ONE) )
      RETURN
      END
