C-----------------------------------------------------------------------
      SUBROUTINE GBPOST(IFW)
C     
C     Since the original routinue to interpolate velocity on the rudder was wrong,
C     This routine was completely regenerated by Hanseong Lee (Sept. 28, 2004)
C
C     This subroutine finds the velocities at the rudder control points from GBFLOW soln. 
C        through interpolation.
C NOTE: if the interpolation point is outside of given data sets,
C       The velocity at that point was assumed to be uniform (u,v,w)=(1.,0.,0.)
C
C -----------------------------------------------------------------------------------

      INCLUDE 'PUFCAV.INC'
      INCLUDE 'PUFCAVC.INC'

      common/domain/ xt(80,80,80),yt(80,80,80),zt(80,80,80)
      common/property/u(80,80,80),v(80,80,80),w0(80,80,80)
      common/postgb/ up(3000),vp(3000),wp(3000)
      common/indices/ni,nj,nk,npanel1
      dimension xp(3000),yp(3000),zp(3000)
      dimension area(6400)

C
C     files
C
      open (unit=9, file='sol-3ds.plt', status='unknown')
      open(unit=11,file='rud.inp',status='unknown')
      open(unit=12,file='contourf.dat',status='unknown')
      open(unit=13,file='contourw.dat',status='unknown')

      open(unit=20,file='S98.DAT',status='unknown')
      open(unit=21,file='S99.DAT',status='unknown')
C
C     location of the rudder wrt propellor
C

      read(11,*)offset
      read(11,*)yscale,yoffset
C
C     reading the sol-3ds.plt
C     
C     Format changed to free format
C
      READ(9,*)
      read(9,*) ni, nj, nk
      write(*,*)"reading sol-3ds i =",ni,"j =",nj,"k = ",nk
      do 10 k=1,nk
         do 10 j=1,nj
            do 20 i=1,ni
               read(9,*) xt(i,j,k), yt(i,j,k), zt(i,j,k),
     +              u(i,j,k), v(i,j,k), w0(i,j,k), dum
 20         continue
 10      continue
         
         close(unit=9)
         
C     reading the foil or wake control points in GB co-ord system

         IF(IFW.EQ.1)THEN
            write(*,*)"Determining flow over foil ",npanel," cpts"
            npanel1=npanel
            
            do 30 i=1,npanel1
               xp(i) = xctp(i,1,1)*yscale+offset
               yp(i) = xctp(i,2,1)*yscale - yoffset
               zp(i) = xctp(i,3,1)*yscale
 30         continue
         ELSEIF(IFW.EQ.2)THEN
            npanel1=NWSUB*MR
            write(*,*)"Determining flow over wake ", npanel1,"cpts"
            i = 0
            do m=1,mr   
               do n=1,nwsub
                  i = i + 1 
                  xp(i) = xws(n,m)*yscale+offset
                  yp(i) = yws(n,m)*yscale - yoffset
                  zp(i) = zws(n,m)*yscale
               enddo
            enddo
         ENDIF   
            
C -- Calculate Area of each panel from GBFLOW GRID at I = 1

         IK = 0
         DO J = 1 , NJ-1
            DO K = 1 , NK-1
               IK = IK + 1
               X1 = YT(1,J,K)
               X2 = YT(1,J,K+1)
               x3 = YT(1,J+1,K+1)
               x4 = yt(1,J+1,K)
               
               y1 = zT(1,J,K)
               y2 = zT(1,J,K+1)
               y3 = zT(1,J+1,K+1)
               y4 = zt(1,J+1,K)

               area1 = tarea(x1,x2,x3,y1,y2,y3)
               area2 = tarea(x1,x3,x4,y1,y3,y4)
               
               area(ik) = abs(area1) + abs(area2)
            enddo
         enddo
         
C -- Check the area which consisted of four grid point and field point
C
C     If this area is larger than the area from four grid point,
C     The field point is outside of that grid.
C
C     Find Node indices (J and K)  which include the field point, 
C     and then find I index
C
C ------------------------------------------------------

         DO I = 1, NPANEL1
            x0 = yp(i)
            y0 = zp(i)
            NJJ = 0
            NKK = 0
            
            ik = 0
            do j = 1 , nj-1
               j1 = j + 1
               do k = 1 , nk-1
                  k1 = k + 1
                  ik = ik + 1

                  X1 = YT(1,J,K)
                  X2 = YT(1,J,K1)
                  X3 = YT(1,J1,K1)
                  X4 = YT(1,J1,K)
                  
                  Y1 = zT(1,J,K)
                  Y2 = zT(1,J,K1)
                  Y3 = zT(1,J1,K1)
                  Y4 = zt(1,J1,K)
 
                  area1 = tarea(x0,x1,x2,y0,y1,y2)
                  area2 = tarea(x0,x2,x3,y0,y2,y3)
                  area3 = tarea(x0,x3,x4,y0,y3,y4)
                  area4 = tarea(x0,x4,x1,y0,y4,y1)
                  
                  areaf = abs(area1)+abs(area2)+abs(area3)+abs(area4)
                  
                  IF(areaf .ge. area(ik)-1.e-5 
     %              .AND. areaf .lt. area(ik)+1.e-5) then
                     NJJ = J
                     NKK = K
                     GO TO 1100
                  ENDIF
               enddo
            enddo

 1100       CONTINUE
            
            IF(NJJ .NE. 0 .AND. NKK .NE. 0) THEN
               DO II = 1 , NI-1
                  IF(XP(I) .GE. XT(II,1,1) 
     %                 .AND. XP(I) .LT. XT(II+1,1,1)) THEN
                     NII = II
                  ENDIF
               ENDDO

               s1 = sqrt( (yp(i)-yt(nii,njj,nkk))**2
     %                    + (zp(i)-zt(nii,njj,nkk))**2 )
               s2 = sqrt( (yp(i)-yt(nii,njj,nkk+1))**2
     %                    + (zp(i)-zt(nii,njj,nkk+1))**2 )
               s3 = sqrt( (yp(i)-yt(nii,njj+1,nkk+1))**2
     %                    + (zp(i)-zt(nii,njj+1,nkk+1))**2 )
               s4 = sqrt( (yp(i)-yt(nii,njj+1,nkk))**2
     %                    + (zp(i)-zt(nii,njj+1,nkk))**2 )

               u1=0.5 * ( 
     %            (s3*u(nii,njj,nkk) + s1*u(nii,njj+1,nkk+1))/(s1+s3)
     %           +(s4*u(nii,njj,nkk+1) + s2*u(nii,njj+1,nkk))/(s4+s2))
               u2=0.5 * ( 
     %            (s3*u(nii+1,njj,nkk)+s1*u(nii+1,njj+1,nkk+1))/(s1+s3)
     %           +(s4*u(nii+1,njj,nkk+1)+s2*u(nii+1,njj+1,nkk))/(s4+s2))

               v1=0.5 * ( 
     %            (s3*v(nii,njj,nkk) + s1*v(nii,njj+1,nkk+1))/(s1+s3)
     %           +(s4*v(nii,njj,nkk+1) + s2*v(nii,njj+1,nkk))/(s4+s2))
               v2=0.5 * ( 
     %            (s3*v(nii+1,njj,nkk)+s1*v(nii+1,njj+1,nkk+1))/(s1+s3)
     %           +(s4*v(nii+1,njj,nkk+1)+s2*v(nii+1,njj+1,nkk))/(s4+s2))

               w1=0.5 * ( 
     %            (s3*w0(nii,njj,nkk) + s1*w0(nii,njj+1,nkk+1))/(s1+s3)
     %           +(s4*w0(nii,njj,nkk+1) + s2*w0(nii,njj+1,nkk))/(s4+s2))
               w2=0.5 * ( 
     %           (s3*w0(nii+1,njj,nkk)+s1*w0(nii+1,njj+1,nkk+1))/(s1+s3)
     %         +(s4*w0(nii+1,njj,nkk+1)+s2*w0(nii+1,njj+1,nkk))/(s4+s2))
C
C
               ddxx1 = abs(xp(i) - xt(nii,1,1))
               ddxx2 = abs(xp(i) - xt(nii+1,1,1))
               
               
               up(i) = (u1*ddxx2 + u2*ddxx1) / (ddxx1+ddxx2)
               vp(i) = (v1*ddxx2 + v2*ddxx1) / (ddxx1+ddxx2)
               wp(i) = (w1*ddxx2 + w2*ddxx1) / (ddxx1+ddxx2)
               
            else
               up(i) = 1.0
               vp(i) = 0.0
               wp(i) = 0.0
            ENDIF
            
         ENDDO

            IF(IFW.EQ.1)THEN
               write(12,93)NC,MR
               do i = 1 ,npanel1
                  write(12,*)xp(i),yp(i),zp(i),up(i),vp(i),wp(i)
                  WRITE(20,*)up(i),vp(i),wp(i)
               enddo   
            ELSEIF(IFW.EQ.2)THEN
               write(13,93)NWSUB,MR
               do i = 1 ,npanel1
                  write(13,*)xp(i),yp(i),zp(i),up(i),vp(i),wp(i)
                  WRITE(21,*)up(i),vp(i),wp(i)
               enddo   
            ENDIF   

 93   format('variables=x,y,z, u,v,w'/
     +     'zone i=',i3,', j=',i3)
            
            close(9)
            close(11)
            close(12)
            close(13)
            CLOSE(20)
            CLOSE(21)        
            
            RETURN
            END


C =========================================
      Function tarea(x1,x2,x3,y1,y2,y3)
C -----------------------------------------

      a1 = x1 * (y2 - y3)
      a2 = x2 * (y3 - y1)
      a3 = x3 * (y1 - y2)

      tarea = 0.5 * abs(a1 + a2 + a3)

      return
      end

