************************************************************************
*    These parameters are necessary for user input camber and          *
*    distribution.                                                     *
*    Copied from PSF10.3 on 11/27/98 by J.Young                        *
************************************************************************
       COMMON /INPGEO1/ XCS(NXMAX,15),XTS(NXMAX,16)
!      COMMON /INPGEO2/ CUBTMP(MAXSPL),
!    *		XCS1(15,MBPZ),XTS1(16,MBPZ),XCS0(MBPZ),XTS0(MBPZ)     

