# Makefile for PROPCAV
# Rewrited for Compatibility with PROPCAV_UNS
# 10/09/2017 by Yiran Su
# propcav is generated by default. To get propcav_uns, use "make uns"
# Files (.o) should be listed in objects_xxx.proj files with the correct sequence 
#               (definition of a module should be listed before use of the module)

FORT = ifort -heap-arrays -qopenmp -g -c -O3 -mcmodel=medium -shared-intel -extend_source 132 -traceback
LINK = ifort -heap-arrays -qopenmp -g -O3 -mcmodel=medium -shared-intel -extend_source 132 -traceback -o
#FORT = ifort -qopenmp -g -c -O3 -mcmodel=medium -shared-intel -extend_source 132 -traceback
#LINK = ifort -qopenmp -g -O3 -mcmodel=medium -shared-intel -extend_source 132 -traceback -o

FILE1 = objects_propcav.proj
FILE2 = objects_uns.proj

RM = rm -f

OBJ1 = $(shell cat $(FILE1))
OBJ2 = $(subst propcav.o,,$(OBJ1))
OBJ3 = $(shell cat $(FILE2))
INC  = $(wildcard *.INC)

propcav: $(OBJ1)
	$(LINK) propcav $(OBJ1)

.PHONY: uns
uns: propcav_uns

all: propcav_uns propcav

propcav_uns: $(OBJ2) $(OBJ3)
	$(LINK) propcav_uns $(OBJ2) $(OBJ3)

%.o: %.f $(INC)
	$(FORT) $<

.PHONY: clean
clean:
	$(RM) *.o
	$(RM) *.mod
	$(RM) propcav propcav_uns

